# -*- coding: utf-8 -*-
"""Peformance_alunos_sweetviz

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15yACFcUDp6LT7IedJiqeGt_bPNSzZZvR

# **Dicionarios de dados**


*   gender :  categorical
*   race/ethinicity : categorical
*   parental level of education: categorical
*   lunch : categorical
*   test preparation course: categorical
*   math score : numerical
*   reading score : numerical
*   writing score: numerical

 Esse Dataset é da plataforma kaggel **Peformance de alunos** - [clique no link](https://www.kaggle.com/code/charlesabe/student-performance-beginner-eda/notebook)
"""

!pip install sweetviz

import sweetviz as sv
import pandas as pd
import webbrowser

#Carregar os dados

import pandas as pd

# Substitua 'nome_do_arquivo.csv' pelo nome do seu arquivo CSV
caminho_do_arquivo = '/content/StudentsPerformance.csv'

# Carregar o arquivo CSV em um DataFrame do pandas
df = pd.read_csv(caminho_do_arquivo)

# Exibir as primeiras linhas do DataFrame para verificar se o arquivo foi carregado corretamente
print(df.head())

# Analise df

report=sv.analyze(df)

report.show_html('eda_report.html')
relatorio_caminho = 'eda_report.html'

# split do df
df1 = df[0:400]
df2 = df[400:]

print(df1.info())

print(df2.info())

report_comp=sv.compare(df1,df2)
report_comp.show_html()

# Comparação dos data frames
report_comp=sv.compare([df1, 'Base Original'], [df2, 'Base em Validação'])

# Gerando report
report_comp.show_html('Compare_Results.html')

# Target Analise

report_comp=sv.compare(df1,df2, 'math score')
report_comp.show_html('Compare_Results.html')

report_comp.show_html(filepath='report.html',
                      open_browser=True,
                      layout='vertical',
                      scale=0.9)